config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, :path => 'users'

 resource :user,  only: [:show] do
   resources :products, only: [:show]
 end

  resources :products do
    get 'buy'
  	resources :transactions, only: [:new, :create]
  end

  resources :transactions, only: [:show, :index]

  get '/services/', to: 'pages#services',  as: 'services'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :transactions
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def services
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_user,
  # before_action :set_product, only: [:show]

  def new
    @product = Product.new
  end

  def create
    @user = current_user
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    # unless asset_exist?(@product.image)
    #   @product.image = 'https://picsum.photos/200/300'
    # end


    if @product.save
    redirect_to product_path(@product), notice: "Seu produto foi adicionado"
    else
    flash[:alert] = "Error"
    render :new
    end


  end

  def index
    @category = params[:category]
    @products = Product.where(category: @category)
  end

  def show
    @product = Product.find(params[:id])
  end

  def buy
    redirect_to product_path(params[:product_id]), notice: "Parabéns, sua compra foi confirmada!"
  end

  # Rotas destroy, edit & update ñ serão utilizadas na apresentação
  # def edit
  # end

  # def destroy
  # end

  # def update
  # end

  private
  def set_user
    @user = current_user
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit( :name, :category, :origin, :quantity, :price, :description , :image, :image_cache)

  end

  def asset_exist?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.save
    redirect_to root_path
  end

  def show
    @products = current_user.products
  end

  # acões edit e update não serão apresentadas
  # def edit
  # end

  # def update
  # end

  private

  def user_params
    params.require(:user).permit( :name, :address, :email, :password, :balance, :avatar )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Trapieer®</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJmoXsLZpDoVYaHxmZ0XZES8yHiC4ycO0"></script>
  </head>
  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer"%>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content text-center">
    <h1 class="animated slideInDown delay-1s">Trapieer®</h1>
    <p>As melhores sementes para cervejeiros artesanais</p>
  </div>
  <div class="text-center arrow-box"><i class="fas fa-chevron-circle-down animated bounce infinite slow"></i></div>
</div>
<br>

<h2 id="home-h2">Principais categorias</h2>

<div class="container">
  <div class="content">
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('http://www.osul.com.br/wp-content/uploads/2016/12/lupulo-870x490.jpg');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Lupulo</h2>
          <p> Aprovado pelos monges! </p>
        </div>
        <%= link_to "", products_path(category:'lupulo'), class: 'card-link' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('http://successostartup.it/wp-content/uploads/2017/06/malto-d-orzo-birra_0.jpg');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Malte</h2>
          <p> Os mais puros que existem! </p>
        </div>
        <%= link_to "", products_path(category:'malte'), class: 'card-link' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('https://img.itdg.com.br/tdg/images/blog/uploads/2017/03/shutterstock_291146909.jpg');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Levedura</h2>
          <p>Para todos os tipos de fermentação</p>
        </div>
        <%= link_to "", products_path(category:'levedura'), class: 'card-link' %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="content">
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('https://imagens.publico.pt/imagens.aspx/1337586?tp=UH&db=IMAGENS&type=JPG&w=837');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Fornecedores</h2>
          <p> Os melhores fornecedores da região! </p>
        </div>
        <%= link_to "", products_path(category:'lupulo'), class: 'card-link' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('https://novonegocio.com.br/wp-content/uploads/2015/03/fabrica-de-cerveja.jpg');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Equipamento</h2>
          <p> Encontre os melhores equipamentos! </p>
        </div>
        <%= link_to "", products_path(category:'malte'), class: 'card-link' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 animated fadeInDown slow">
      <div class="card_category" id="anchor" style="background-image: linear-gradient(-225deg, rgba(255,127,0,0.6) 0%, rgba(0,36,61,0.3) 50%), url('http://www.4truck.com.br/blog/wp-content/uploads/2017/12/ba%C3%BA-de-caminh%C3%A3o-transporte-de-carga.jpg');">
        <a class="card-link" href="#"></a>
        <div class="card-description">
          <h2>Serviços</h2>
          <p> Serviços p/ todos os tipos de cervejeiros! </p>
        </div>
        <%= link_to "", services_path, class: 'card-link' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/services.html.erb
<div class="container">
  <h6><%= link_to 'Home', root_path %> / <%= link_to 'Categorias', root_path %> / <strong> Serviços </strong></h6>
  <div class="row" style="display: flex; margin-top: 3em;">
    
      <div class="card-service">
        <div class="card-service-top">
          <div class="card-service-top-image" style="background-image: url('https://source.unsplash.com/featured/?car,ride')">
              <i class="fas fa-heart position-icon"></i>
          </div>
          <div class="card-service-info">
            <div>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="far fa-star"></i>
            </div>
            <p><strong>Fancy service</strong></p>
            <span>It's the best service, you should buy it!</span>
            <a href="" class="btn-green">£200</a>
          </div>
        </div>

        <img class="card-service-middle" src="https://source.unsplash.com/featured/?engine,mechanic" alt="">

        <div class="card-service-bottom">
          <img src="https://source.unsplash.com/featured/?mechanic" alt="" class="">
          <img src="https://source.unsplash.com/featured/?harley" alt="" class="">
          <img src="https://source.unsplash.com/featured/?car,ride" alt="" class="">
        </div>
      </div>
      <div class="card-service">
        <div class="card-service-top">
          <div class="card-service-top-image" style="background-image: url('https://source.unsplash.com/featured/?car,ride')">
              <i class="fas fa-heart position-icon"></i>
          </div>
          <div class="card-service-info">
            <div>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="far fa-star"></i>
            </div>
            <p><strong>Fancy service</strong></p>
            <span>It's the best service, you should buy it!</span>
            <a href="" class="btn-green">£200</a>
          </div>
        </div>

        <img class="card-service-middle" src="https://source.unsplash.com/featured/?engine,mechanic" alt="">

        <div class="card-service-bottom">
          <img src="https://source.unsplash.com/featured/?mechanic" alt="" class="">
          <img src="https://source.unsplash.com/featured/?harley" alt="" class="">
          <img src="https://source.unsplash.com/featured/?car,ride" alt="" class="">
        </div>
      </div>
      <div class="card-service">
        <div class="card-service-top">
          <div class="card-service-top-image" style="background-image: url('https://source.unsplash.com/featured/?car,ride')">
              <i class="fas fa-heart position-icon"></i>
          </div>
          <div class="card-service-info">
            <div>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="far fa-star"></i>
            </div>
            <p><strong>Fancy service</strong></p>
            <span>It's the best service, you should buy it!</span>
            <a href="" class="btn-green">£200</a>
          </div>
        </div>

        <img class="card-service-middle" src="https://source.unsplash.com/featured/?engine,mechanic" alt="">

        <div class="card-service-bottom">
          <img src="https://source.unsplash.com/featured/?mechanic" alt="" class="">
          <img src="https://source.unsplash.com/featured/?harley" alt="" class="">
          <img src="https://source.unsplash.com/featured/?car,ride" alt="" class="">
        </div>
      </div>
          
  </div>
</div>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="title"> Cadastre seu Produto </h1>
      <p id="sub-cadastro"> Preencha o formulário para cadastrar seu insumo </p>
      <%= simple_form_for(@product) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <br>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :category,:collection => %w[lupulo malte levedura], required: true %>
          <%= f.input :origin %>
          <%= f.input :quantity %>
          <%= f.input :price %>
          <%= f.input :description %>
          <%= f.input :image %>
        </div>
        <br>
        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-warning lgn-btn' %>
        </div>
      <% end %>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <h6><%= link_to 'Home', root_path %> / <%= link_to 'Categorias', root_path %> / <strong> <%= @category.capitalize%> </strong></h6>
  <div class="row">
  <div class="row">
    <% @products.each do |product| %>
      <% if product.image.present?  %>
      <%   x = product.image %>
      <% else %>
      <%   x = 'ngfqmiujsrwlhlmvu66l'  %>
      <% end %>
      <div class="col-xs-12 col-sm-6 col-md-3 card-product animated fadeInLeft">
        <!-- <div class="card" id="anchor" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path x %> ) ;"> -->
        <div class="card" id="anchor" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= product.image %>);">
          <div class="card-description">
            <h2><%= product.name.capitalize %></h2>
          </div>
          <%= link_to "", product_path(product.id), class: 'card-link' %>
        </div>
        <div class="card-params">
          <div class="product-details">
            <h5>Origem: <%= product.origin.capitalize %></h5>
            <h5>Tipo: <em><%= product.category.capitalize %></em></h5>
            <h5>Preço/Kg: $<strong><%= product.price %>,<%= rand(10..31) %></strong></h5>
            <h5>Anunciado há: <strong><%= rand(10..31) %><strong> dias</h5>
          </div>
          <div class="stars">
            <% rand(1...5).times do %>
              <i class="fas fa-star"></i>
            <% end %>
          </div>
          <div class="product-btn"><%= link_to "Ver Mais", product_path(product.id), class: 'btn btn-primary card-btn animated'%></div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/products/new.html.erb
      <%= render 'form', product: @product %>

app/views/products/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">
  <h6>Home / Categorias / <%= @product.category.capitalize %> / <strong><%= @product.name.capitalize %></strong></h6>
  <div class="show-product animated fadeInUp slow">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
      <div class="product-img animated fadeInLeft slow">
      <%if @product.image.present? %>
        <%= cl_image_tag( @product.image,                 width: 300, height: 300, crop: :fill) %>
        <%else%>
        <%= cl_image_tag('ngfqmiujsrwlhlmvu66l',          width: 300, height: 300, crop: :fill) %>
        <%end%>
        </div>
      </div>
    <div class="col-xs-12 col-sm-6">
      <div class="product-components">
        <h2><%=@product.name.capitalize%></h2>
        <p>Origem: <%=@product.origin.capitalize%></p>
        <p><%=@product.description%></p>
        <p>Quantidade: <%=@product.quantity%>kg</p>
        <p>R$ <%=@product.price%>/kg</p>
          <% if user_signed_in? %>
            <% x = product_buy_path(params[:id])  %>
          <% else %>
            <% x = new_user_session_path %>
          <% end %>
        <p><%= link_to 'Comprar', x , class: "btn btn-success lgn-btn" %></p>
        <p><%= link_to 'Voltar', products_path(category: @product.category), class: "btn btn-danger btn-sm", style: "opacity: 0.6; width: 100px;"%></p>
      </div>
    </div>
  </div>
</div>
  <div class="animated fadeInLeft slow" id="map" style="width:100%;height:500px"></div>
    <script>
    function myMap() {
    var mapCanvas = document.getElementById("map");
    var myCenter = new google.maps.LatLng(-23.551378,-46.638090);
      var mapOptions = {center: myCenter, zoom: 15};
      var map = new google.maps.Map(mapCanvas, mapOptions);
      var marker = new google.maps.Marker({
        position: myCenter,
        animation: google.maps.Animation.BOUNCE});
      marker.setMap(map);
    }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBV11HPtIcmMl4mTFeD1fz75ZXj2cFrnJ8&callback=myMap"></script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This site is made with <i class="fas fa-beer"></i> by Monges Trapistas
  </div>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar-wagon">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i id="logo-nav" class="fab fa-pagelines" ></i>
    <!-- Search Bar -->
    <!-- <div id="wrap">
      <form action="" autocomplete="on">
        <input id="search" name="search" type="text" placeholder="Em que podemos lhe ajudar?"><input id="search_submit" value="Rechercher" type="submit">
      </form>
    </div> -->
    <!-- Right Navigation -->

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Histórico", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Meus Produtos", user_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Vender Produtos", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/karinamerulla", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <!-- Dropdown appearing on mobile only -->
        <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><a href="#">Host</a></li>
              <li><a href="#">Trips</a></li>
              <li><a href="#">Messagese</a></li>
            </ul>
          </div>
        </div>
      </div> -->
    <% end %>
  </div>
  <% end %>
  </div>

app/views/shared/_subscribe.html.erb
<!-- <p><%= link_to 'Registrar-se', new_user_registration_path, class: "btn btn-treehouse", id:"home-btn"%></p> -->
<div style="display: flex;">
  <div style="justify-content: flex-end;">
    <% unless user_signed_in? %>
      <p><%= link_to 'Inscreva-se', new_user_registration_path, class: "btn btn-treehouse animated pulse infinite slower", id:"home-btn"%></p>
    <% end  %>
  </div>
</div>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>

app/views/users/_form.html.erb
<div class="container">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :avatar %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :address %>
      <%= f.input :balance %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/users/_form_signin.html.erb
<div class="container">
	<%= simple_form_for(@user) do |f| %>
	  <%= f.error_notification %>
	  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

	  <div class="form-inputs">
	    <%= f.input :name %>
	    <%= f.input :email %>
	    <%= f.input :password %>
	  </div>

    <p>fdp!</p>

	  <div class="form-actions">
	    <%= f.button :submit %>
	  </div>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New user</h1>

	<% if @user.errors.any? %>
	<p>You have the following errors:</p>
	  <%= @user.errors.messages %>
	<% end %>

	<%= render 'form', user: @user %>
	
	<%= link_to 'Back', root_path %>
</div>

app/views/users/show.html.erb
<h2><%= current_user.name %>, seguem seus produtos </h2>

<div class="container">
  <h6>home / meus produtos
  <div class="row">
  <div class="row">
    <% @products.each do |product| %>
      <% if product.image.present?  %>
      <%   x = product.image %>
      <% else %>
      <%   x = 'ngfqmiujsrwlhlmvu66l'  %>
      <% end %>
      <div class="col-xs-12 col-sm-6 col-md-3 card-product animated fadeInLeft">
        <div class="card" id="anchor" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path x %> ) ;">
          <div class="card-description">
            <h2><%= product.name.capitalize %></h2>

          </div>
          <%= link_to "", product_path(product.id), class: 'card-link' %>
        </div>
        <div class="card-params">
          <div class="product-details">
            <h5>Origem: <%= product.origin.capitalize %></h5>
            <h5>Tipo: <%= product.category.capitalize %></h5>
            <h5>Preço/Kg: $<%= product.price %></h5>
            <h5>Anunciado há: <strong><%= rand(10..31) %><strong> dias</h5>
          </div>
          <div class="stars">
            <% rand(1...5).times do %>
              <i class="fas fa-star"></i>
            <% end %>
          </div>
          <div class="product-btn"><%= link_to "Ver Mais", product_path(product.id), class: 'btn btn-primary card-btn animated'%></div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>